
package com.thp.fountain;

public enum FNTypes {
	NONE, SCENE_HEADING, ACTION, CHARACTER, DIALOGUE,
	PARENTHETICAL, DUAL_DIALOG, TRANSITION, CENTERED_TEXT,
	PAGE_BREAK, SECTION_HEADING, SYNOPSIS, COMMENT, BONEYARD 
}